services:
  web:
    build: ./apserver
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/myproject
    volumes:
      - ./apserver:/app
    tty: true
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - POSTGRES_DB=todos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=todos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
